/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      sans: ["Inter", "sans-serif"],
      montserrat: ["Montserrat"],
      inter: ["Inter"],
    },
    extend: {
      colors: {
        primary: "#7505E0",
        primary2: "#AE76FF",
        primary3: "#C7A7FF",
        primary4: "#DECEFF",
        primary5: "#EEE5FF",
        primary6: "#F5F1FF",
        secondary: "#15555A",
        secondary2: "#1BAFB1",
        secondary3: "#33CCCC",
        secondary4: "#9DF2EC",
        secondary5: "#CEF9F5",
        secondary6: "#F1FCFB",
        accent: "#18243E",
        neutral: "#0A0A0A",
        neutral2: "#4F4F4F",
        neutral3: "#6D6D6D",
        neutral4: "#B0B0B0",
        neutral5: "#E7E7E7",
        neutral6: "#F6F6F6",
        disabled: "#888FA8",
        blueNavy: "#3A558D",
      },
      fontWeight: {
        hairline: 100,
        thin: 200,
        extraLight: 300,
        light: 400,
        normal: 500,
        medium: 600,
        semibold: 700,
        bold: 800,
        extrabold: 900,
      },
      fontSize: {
        "display-lg": "112px",
        "display-md": "88px",
        "display-sm": "64px",
        "heading-1": "56px",
        "heading-2": "40px",
        "heading-3": "36px",
        "heading-4": "32px",
        "heading-5": "28px",
        "heading-6": "16px",
        "p-xl": "20px",
        "p-lg": "18px",
        "p-base": "16px",
        "p-sm": "14px",
        "p-xs": "12px",
      },
    },
  },
  plugins: [],
};
